var LitresBookData={},LitRes=LitRes||{};LitRes.Config={lfrom:'',link:'litreslink',noload:'noload',popup:'LitresPopup',width:screen.width<560?'100%':'559px',height:false,overlay:'LitresOverlay',iframe:'LitresIframe',closepopup:'LitresClose',host:'//www.litres.ru',or4:false,newFund:false,iframeApp:false};LitRes.Utils={extend:function(a,b){for(var key in b)
if(b.hasOwnProperty(key))
a[key]=b[key];return a;},getElementsByClassName:function(className){if(typeof document.getElementsByClassName!='function'){if(!className)return[];var elements=document.getElementsByTagName('a');var list=[];var expr=new RegExp('(^|\\b)'+className+'(\\b|$)');for(var i=0,length=elements.length;i<length;i++){if(expr.test(elements[i].className))
list.push(elements[i]);}
return list;}else{return document.getElementsByClassName(className);}},hasClass:function(el,cls){for(var c=el.className.split(' '),i=c.length-1;i>=0;i--){if(c[i]==cls)return true;}
return false;}};LitRes.Widget={iframe:false,overlay:false,popup:false,CreateFrame:function(ArtID,purchased){if(!this.overlay){var lit_overlay=document.createElement('div'),lit_popup=document.createElement('div'),iframe=document.createElement('iframe'),c=document.createElement('a'),styleNode=document.createElement('style');styleNode.type="text/css";var css='#'+LitRes.Config.overlay+'{position:fixed;top:0;left:0;width:100%;height:100%;z-index:10099;background:url('+LitRes.Config.host+'/static/img/widget/black50.png) repeat 0 0;}';css+='#'+LitRes.Config.popup+'{width:'+LitRes.Config.width+';position:absolute;background:#fff;color:#000;z-index:10100;border:1px solid #DBDBDB;padding:17px 0;}';css+='#'+LitRes.Config.closepopup+'{opacity:0.5;width:17px;height:17px;position:absolute;top:7px;right:6px;cursor:pointer;display:block;background:url('+LitRes.Config.host+'/static/new/i/new/bubble-close2.gif) no-repeat 0 0;}';css+='#'+LitRes.Config.closepopup+':hover{opacity:1;}';css+='#'+LitRes.Config.iframe+'{width:100%;height:100%;border:0 none;overflow:hidden; box-sizing:border-box; padding:0 21px;}';if(styleNode.styleSheet)styleNode.styleSheet.cssText=css;else styleNode.appendChild(document.createTextNode(css));document.getElementsByTagName('head')[0].appendChild(styleNode);lit_overlay.id=LitRes.Config.overlay;document.body.appendChild(lit_overlay);lit_overlay.onclick=function(){this.style.display='none';};lit_popup.id=LitRes.Config.popup;lit_overlay.appendChild(lit_popup);lit_popup.onclick=function(e){if(!e)var e=window.event;e.cancelBubble=true;e.returnValue=false;};c.id=LitRes.Config.closepopup;lit_popup.appendChild(c);c.onclick=function(){LitRes.Widget.Hide();}
iframe.id=LitRes.Config.iframe;iframe.scrolling="no";lit_popup.appendChild(iframe);this.overlay=document.getElementById(LitRes.Config.overlay);this.popup=document.getElementById(LitRes.Config.popup);this.iframe=document.getElementById(LitRes.Config.iframe);}
if(ArtID){var iframe_url=LitRes.Config.host+
'/pages/quick_buy_frame/?art='+ArtID+'&widget=1';if(LitRes.Config.iframeApp){iframe_url+='&iframeApp=1';}
this.iframe.src=LitRes.Widget.SetLink(iframe_url);if(LitRes.Config.or4)this.iframe.src+='&or4=1';if(LitRes.Config.newFund)this.iframe.src+='&fund=new';this.iframe.style.opacity=0;document.getElementById(LitRes.Config.popup).style.height=LitRes.Config.height?LitRes.Config.height:'600px'
this.iframe.onload=function(){LitRes.Widget.iframe.style.opacity=1;}}
this.Show(purchased);},Hide:function(){this.overlay.style.display='none';},Show:function(purchased){this.overlay.style.display='block';this.popup.style.top=Math.abs(this.overlay.clientHeight-this.popup.clientHeight)/4+'px';this.popup.style.left=(this.overlay.clientWidth-this.popup.clientWidth)/2+'px';},receiveSize:function(e){if(!LitRes.Config.height&&/^LitWid_([0-9]*(\.[0-9]+)?)$/.test(e.data)){var regex=e.data.match(/^LitWid_([0-9]*(\.[0-9]+)?)$/);if(regex[1]>0){document.getElementById(LitRes.Config.popup).style.height=regex[1]+"px";}}},SetLink:function(o){return o+((LitRes.Config.lfrom.length)?((/\?/.test(o))?'&':'?')+'lfrom='+LitRes.Config.lfrom:'');},LoadArtsData:function(data_obj){var s=document.createElement('script'),id_arr=[];for(var key in data_obj){id_arr.push(key)};s.type='text/javascript';s.async=true;s.src=LitRes.Config.host+'/pages/widgetjs_arts/?art='+id_arr;s.onload=s.onreadystatechange=function(){for(var k in data_obj){if(LitresBookData[k]&&((LitresBookData[k].avail&&!LitresBookData[k].formats)||(LitresBookData[k].purchased&&LitresBookData[k].formats))){for(var i=0;i<data_obj[k].length;i++){if(!LitRes.Utils.hasClass(data_obj[k][i],LitRes.Config.noload)){var txt_inner='Скачать «'+LitresBookData[k].title+'»';if(LitresBookData[k].purchased&&LitresBookData[k].formats){txt_inner+=' в формате '+LitresBookData[k].formats[0];}else if(LitresBookData[k].purchased==='undefined'||LitresBookData[k].purchased==false){txt_inner+=' с ЛитРес за '+LitresBookData[k].price+'р.';}
data_obj[k][i].innerHTML=txt_inner;}
LitRes.Widget.SetPopup(data_obj[k][i],k,LitresBookData[k].purchased);}}}}
var x=document.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);},SetPopup:function(el,ArtID,purchased){el.onclick=function(){LitRes.Widget.CreateFrame(ArtID,purchased);return false;};return el.href=LitRes.Widget.SetLink(el.href);},Parse:function(o){var regex=/^(?:(?:http(?:s)?:)?\/\/)?(?:www.)?(?:litres.ru\/)(\d+)/;if(o.indexOf("art=")>-1){regex=/art=([0-9]+)/i
return o.match(regex)[1]}else if(regex.test(o)){return o.match(regex)[1]}
return regex.test(o)?o.match(regex)[1]:false;},Init:function(setup){LitRes.Utils.extend(LitRes.Config,setup);if(!LitRes.Setup.host)
LitRes.Config.host=(/\blitres.ru$/.test(window.location.host))?'//'+window.location.host:'//www.litres.ru';var el=LitRes.Utils.getElementsByClassName(LitRes.Config.link),el_length=el.length,data_obj={};for(var i=0;i<el_length;i++){var o=LitRes.Widget.Parse(el[i].getAttribute('href'));if(o){data_obj[o]=data_obj[o]||[];data_obj[o].push(el[i]);}}
if(data_obj.length==0)return true;LitRes.Widget.LoadArtsData(data_obj);},Start:function(){LitRes.Widget.Init(LitRes.Setup);}};window.onload=function(){if(location.hostname=='vkapp.litres.ru'||location.hostname=='okapp.litres.ru'){LitRes.Config.iframeApp=true;}
LitRes.Widget.Start();}
window.addEventListener("message",LitRes.Widget.receiveSize,false);